# ----
# Site

title: nakDS
description: Design System
url: https://example.com
google_analytics_key:
permalink: pretty

collections:
  nakDS:
    title: Intro
    position: 1
  core:
    title: Core
    position: 2
  custom:
    title: Custom
    position: 5
  utilities:
    title: Utilities
    position: 3
  designTokens:
    title: Design tokens
    position: 4
  about:
    title: About
    position: 6
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - markdown

exclude:
  - readme.md
  - LICENCE
  - dest
  - docs
  - nakDS-src/
  - node_modules
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - TODO

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - component
  - utility
  - layout
  - object
  - global
  - theme
  - scope
  - state
  - token
